---
# tasks file for ngnix
- name: Install nginx
  become: yes
  yum:
    name: nginx
    state: present

- name: start nginx and ensure it's enabled
  service:
    name: nginx
    state: started
    enabled: yes

- name: Install PHP
  yum:
    name:
      - php
      - php-mysqlnd
      - php-gd
      - php-curl
    state: present