pipeline {
    agent any

    parameters {
        string (name: 'env', defaultValue: 'dev',  description: 'This is the inventory file for the environment to deploy configuration')
        }

    environment {
        ANSIBLE_CONFIG="${WORKSPACE}/deploy/ansible.cfg"
            }

    

    stages {
        stage("Initial cleanup") {
            steps {
                dir("${WORKSPACE}") {
                deleteDir()
                    }
                }
            }

        stage ('Checkout SCM') {
            steps{
                git branch: 'main', url: 'https://github.com/kebsOps/ansible-config-mgt.git'
            }
        }


        stage ('Prepare Ansible For Execution') {
            steps {
            sh ('sudo sed -i -e "/roles_path = \\/[a-z]*\\/*/a\\roles_path = $cpath" -e "/roles_path = \\/[a-z]*\\/*/d" /etc/ansible/ansible.cfg')
            }
        }

        stage ('Run Ansible playbook') {
            steps {
            ansiblePlaybook become: true, colorized: true, credentialsId: 'private-key', disableHostKeyChecking: true, installation: 'ansible', inventory: 'inventory/${env}', playbook: 'playbooks/site.yml'
            }
        }

        stage ('Clean Workspace after build') {
            steps {
            cleanWs(cleanWhenAborted: true, cleanWhenFailure: true, cleanWhenNotBuilt: true, cleanWhenUnstable: true, deleteDirs: true)
            }
        }
    }
}